set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m3)

set(TOOLCHAIN_PREFIX arm-none-eabi-)

set(ARM_GNU_TOOLCHAIN_BIN_DIR "" CACHE PATH "Directory that contains the Arm GNU bare-metal binaries")

if(NOT ARM_GNU_TOOLCHAIN_BIN_DIR)
	if(EXISTS "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-gcc")
		set(ARM_GNU_TOOLCHAIN_BIN_DIR "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin")
	endif()
endif()

if(ARM_GNU_TOOLCHAIN_BIN_DIR)
	set(TOOLCHAIN_COMMAND_PREFIX "${ARM_GNU_TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}")
else()
	set(TOOLCHAIN_COMMAND_PREFIX ${TOOLCHAIN_PREFIX})
endif()

if(ARM_GNU_TOOLCHAIN_BIN_DIR)
	set(_ARM_GNU_TOOLCHAIN_HINTS "${ARM_GNU_TOOLCHAIN_BIN_DIR}")
else()
	set(_ARM_GNU_TOOLCHAIN_HINTS)
endif()

find_program(ARM_NONE_EABI_GCC NAMES ${TOOLCHAIN_PREFIX}gcc HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} REQUIRED NO_CACHE)
find_program(ARM_NONE_EABI_AR NAMES ${TOOLCHAIN_PREFIX}ar HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} REQUIRED NO_CACHE)
find_program(ARM_NONE_EABI_RANLIB NAMES ${TOOLCHAIN_PREFIX}ranlib HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} REQUIRED NO_CACHE)
find_program(ARM_NONE_EABI_NM NAMES ${TOOLCHAIN_PREFIX}nm HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} REQUIRED NO_CACHE)
find_program(ARM_NONE_EABI_OBJCOPY NAMES ${TOOLCHAIN_PREFIX}objcopy HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} REQUIRED NO_CACHE)
find_program(ARM_NONE_EABI_SIZE NAMES ${TOOLCHAIN_PREFIX}size HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} REQUIRED NO_CACHE)
find_program(ARM_NONE_EABI_OBJDUMP NAMES ${TOOLCHAIN_PREFIX}objdump HINTS ${_ARM_GNU_TOOLCHAIN_HINTS} NO_CACHE)

set(CMAKE_C_COMPILER "${ARM_NONE_EABI_GCC}" CACHE FILEPATH "C compiler" FORCE)
set(CMAKE_ASM_COMPILER "${ARM_NONE_EABI_GCC}" CACHE FILEPATH "ASM compiler" FORCE)
set(CMAKE_AR "${ARM_NONE_EABI_AR}" CACHE FILEPATH "Archiver" FORCE)
set(CMAKE_RANLIB "${ARM_NONE_EABI_RANLIB}" CACHE FILEPATH "Ranlib" FORCE)
set(CMAKE_NM "${ARM_NONE_EABI_NM}" CACHE FILEPATH "nm tool" FORCE)
set(CMAKE_OBJCOPY "${ARM_NONE_EABI_OBJCOPY}" CACHE FILEPATH "objcopy tool" FORCE)
set(CMAKE_SIZE "${ARM_NONE_EABI_SIZE}" CACHE FILEPATH "size tool" FORCE)

if(ARM_NONE_EABI_OBJDUMP)
	set(CMAKE_OBJDUMP "${ARM_NONE_EABI_OBJDUMP}" CACHE FILEPATH "objdump tool" FORCE)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-m3 -mthumb")
set(CMAKE_ASM_FLAGS_INIT "-mcpu=cortex-m3 -mthumb -x assembler-with-cpp")

set(CMAKE_EXECUTABLE_SUFFIX_C ".elf")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)